# Generated by Django 2.2.1 on 2019-05-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('devicename', models.CharField(max_length=200)),
                ('devicetype', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('osversion', models.CharField(max_length=200)),
                ('timecheckedout', models.DateTimeField(verbose_name='date checked out')),
                ('checkedoutby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date action occurred')),
                ('checkedoutby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Device')),
            ],
        ),
    ]
