# Generated by Django 2.2.1 on 2019-05-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='devicename',
        ),
        migrations.AlterField(
            model_name='device',
            name='checkedoutby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.User'),
        ),
        migrations.AlterField(
            model_name='device',
            name='timecheckedout',
            field=models.DateTimeField(null=True, verbose_name='date checked out'),
        ),
    ]
